apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.collectors.telegrafIngress.name }}"
  annotations:
  {{- if .Values.collectors.telegrafIngress.service.annotations }}
  {{- toYaml .Values.collectors.telegrafIngress.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.collectors.telegrafIngress.service.type }}
  {{- if and .Values.collectors.telegrafIngress.service.loadBalancerIP (eq .Values.collectors.telegrafIngress.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.collectors.telegrafIngress.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: 57400-tcp
    protocol: TCP
    port: 57400
    targetPort: 57400
    {{- if and .Values.collectors.telegrafIngress.service.nodePort (eq .Values.collectors.telegrafIngress.service.type "NodePort") }}
    nodePort: {{ .Values.collectors.telegrafIngress.service.nodePort }}
    {{- end }}
  selector:
    app: "{{ .Values.collectors.telegrafIngress.name }}"