# Self maintained charts /template
ingressSecretName: ingress-certificate-secret-prod

collectors:
  gobmp:
    name: gobmp
    replicas: 1
    image: docker.io/sbezverk/gobmp:latest
    ## 'port' (and optionally 'nodePort') of service
    ports:
      incomingBMPSessions: 30511
      performanceMonitoring: 30767
    resources:
      requests:
        memory: 50Mi
        cpu: 10m
      limits:
        memory: 1024Mi
        cpu: 1
    service:
      ## Service type can be one of { ClusterIP, LoadBalancer, NodePort }
      type: LoadBalancer
      ## Configuration for service type 'LoadBalancer'
      loadBalancerIP: 172.16.19.64
      ## Configuration for service type 'ClusterIP'
      # clusterIP: 10.152.183.244
      ## Optional annotations
      annotations:
        metallb.universe.tf/address-pool: load-balanced

  telegrafIngress:
    name: telegraf-ingress
    replicas: 1
    image: docker.io/telegraf:1.29-alpine
    imagePullSecret: regcred
    ## 'port' (and optionally 'nodePort') of service
    port: 32400
    # resources:
    #   requests:
    #     memory:
    #     cpu:
    #   limits:
    #     memory:
    #     cpu:
    service:
      ## Service type can be one of { ClusterIP, LoadBalancer, NodePort }
      type: LoadBalancer
      ## Configuration for service type 'LoadBalancer'
      loadBalancerIP: 172.16.19.65
      ## Configuration for service type 'ClusterIP'
      # clusterIP: 10.152.183.1
      ## Optional annotations
      annotations:
        metallb.universe.tf/address-pool: load-balanced

processors:
  lslinknodeEdge:
    name: lslinknode-edge
    replicas: 1
    image: ghcr.io/jalapeno-api-gateway/jalapeno/lslinknode-edge:v1.0.0
    # resources:
    #   requests:
    #     memory:
    #     cpu:
    #   limits:
    #     memory:
    #     cpu:
  linkstateEdge:
    name: linkstate-edge
    replicas: 1
    image: docker.io/iejalapeno/linkstate-edge:latest
    # resources:
    #   requests:
    #     memory:
    #     cpu:
    #   limits:
    #     memory:
    #     cpu:
  telegrafEgress:
    name: telegraf-egress
    replicas: 1
    image: docker.io/telegraf:1.29-alpine
    imagePullSecret: regcred
    # resources:
    #   requests:
    #     memory:
    #     cpu:
    #   limits:
    #     memory:
    #     cpu:
  topology:
    name: topology
    replicas: 1
    image: ghcr.io/jalapeno-api-gateway/jalapeno/topology:v1.0.0
    # resources:
    #   requests:
    #     memory:
    #     cpu:
    #   limits:
    #     memory:
    #     cpu:

arangodb:
  image:
    registry: docker.io
    repository: arangodb
    tag: 3.11.7
  arangodb:
    service:
      type: ClusterIP
    #   nodePorts:
    #     http: 30852
  ingress:
    enabled: true
    hostname: arango.dev.network.garden
  auth:
    admin:
      username: root
      password: jalapeno
      
  databaseName: jalapeno
  databaseUser: root
  databasePassword: jalapeno

# Official bitnami/stable charts
# The charts are defined in the Charts.yaml as dependency

# https://github.com/bitnami/charts/tree/master/bitnami/influxdb
influxdb:
  fullnameOverride: influxdb
  image:
    repository: bitnami/influxdb
    #tag: 2.0.7-debian-10-r34
    tag: 1.8.5 # newest release for oldest influxdb version
  auth:
    admin:
      username: admin
      password: gsplabgsplab
  influxdb:
    extraEnvVars:
      # Don't change the ordering!
      # - name: INFLUXDB_DB
      #   value: "mdt_db"
      # - name: INFLUXDB_USER
      #   value: jalapeno
      # - name: INFLUXDB_USER_PASSWORD
      #   value: jalapeno
      - name: INFLUXDB_DB
        value: "mdt_db"
      - name: INFLUXDB_USER
        value: "jalapeno"
      - name: INFLUXDB_USER_PASSWORD
        value: "jalapeno"
    replicaCount: 1
    # service:
    #   type: NodePort
    #   nodePorts:
    #     http: 30308
    service:
      type: ClusterIP
      ports:
        http: 8086
        rpc: 8088

# https://github.com/bitnami/charts/tree/master/bitnami/grafana
grafana:
  fullnameOverride: grafana
  image:
    repository: bitnami/grafana
    tag: 10.3.1-debian-11-r2
  admin:
    user: root
    password: jalapeno
  replicaCount: 1
  # service:
  #   type: NodePort
  #   nodePort: 30300
  service:
    type: ClusterIP
    ports:
      grafana: 3000
  ingress:
    enabled: true
    hostname: grafana.dev.network.garden
    tls:
      - hosts:
        - grafana.dev.network.garden
        secretName: ingress-certificate-secret-prod

# https://github.com/bitnami/charts/tree/master/bitnami/kafka
kafka:
  fullnameOverride: kafka
  image:
    repository: bitnami/kafka
    tag: 2.8.0-debian-10-r57
  replicacount: 1
  # service:
  #   type: NodePort
  # externalAccess:
  #   enabled: true
  #   service:
  #     type: NodePort
  #     nodePorts:
  #       - 30092
